# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PayBaymaxChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayBaymaxChallenge

  target 'PayBaymaxChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PayBaymaxChallengeUITests' do
    pod 'RxBlocking', '~> 5.1.1'
  end
  
  pod 'Alamofire', '~> 5.4'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Swinject'
  pod 'ReachabilitySwift'
  pod 'MBProgressHUD', '~> 1.2'
  pod 'IQKeyboardManager'
  
end
